### PR TITLE
Support no application in Gitops 

### PR DESCRIPTION
**Pull request by maysunfaisal**
### What does this PR do?:

Adds in the condition to only include deployment, svc and patches only if the software template supports an application

### Which issue(s) this PR fixes:

https://issues.redhat.com/browse/RHDHPAI-84

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened and linked to this PR, if they are not in the PR scope due to various constraints.

- [x] Tested and Verified

  

- [ ] Documentation (READMEs, Product Docs, Blogs, Education Modules, etc.)

### CODE REVIEW

**Review by thepetk — COMMENTED** [review]
In general it looks good to me. One question I have is about the RHOAI case. Do we still include this option when we want to use mode-only templates?

**Review by Jdubrick — APPROVED** [review]
lgtm after @thepetk comment is addressed

**Comment by maysunfaisal** [comment]
> In general it looks good to me. One question I have is about the RHOAI case. Do we still include this option when we want to use mode-only templates?

@thepetk no, we will not have RHOAI when using the model only template https://github.com/redhat-ai-dev/ai-lab-template/pull/59/files#diff-038b60ac0d362ec74cc87d6a4ce2bcab17138991fe8e777b37924900060c3326R31

**Comment by thepetk** [comment]
> > In general it looks good to me. One question I have is about the RHOAI case. Do we still include this option when we want to use mode-only templates?
> 
> @thepetk no, we will not have RHOAI when using the model only template

Yeah I was guessing this should be it. So, do you think we should add an "and" condition when we re importing the rhoai directory ([here](https://github.com/redhat-ai-dev/ai-lab-app/blob/main/templates/http/base/kustomization.yaml#L27)). I'm on the fence if it's redudant or the supportApp automatically means that we don't support RHOAI. WDYT?

**Comment by maysunfaisal** [comment]
> > > In general it looks good to me. One question I have is about the RHOAI case. Do we still include this option when we want to use mode-only templates?
> > 
> > 
> > @thepetk no, we will not have RHOAI when using the model only template
> 
> Yeah I was guessing this should be it. So, do you think we should add an "and" condition when we re importing the rhoai directory ([here](https://github.com/redhat-ai-dev/ai-lab-app/blob/main/templates/http/base/kustomization.yaml#L27)). I'm on the fence if it's redudant or the supportApp automatically means that we don't support RHOAI. WDYT?

@thepetk We don't need the condition. Thanks for the idea however, I have updated my Templates PR a bit and this is now gated by a `SUPPORT_APP` flag (Previously I had two flags, one for app support and one for RHOAI but you are right, RHOAI is only supported for apps right now) https://github.com/redhat-ai-dev/ai-lab-template/pull/59/files#diff-93f04871150a5282f08197ca6fb62209045c4db3f3c3a4b6a8b8abd09a8c4601R398-R401

and this is the Gitops Kustomize, there is no `rhoai` reference https://github.com/redhat-appstudio-mjf/modelserver-dec17-1-gitops/blob/main/components/modelserver-dec17-1/base/kustomization.yaml

**Comment by maysunfaisal** [comment]
merging this PR, since we dont need a condition for RHOAI, it's gated by the SUPPORT_APP flag in Templates

**Comment by thepetk** [comment]
> > > > In general it looks good to me. One question I have is about the RHOAI case. Do we still include this option when we want to use mode-only templates?
> > > 
> > > 
> > > @thepetk no, we will not have RHOAI when using the model only template
> > 
> > 
> > Yeah I was guessing this should be it. So, do you think we should add an "and" condition when we re importing the rhoai directory ([here](https://github.com/redhat-ai-dev/ai-lab-app/blob/main/templates/http/base/kustomization.yaml#L27)). I'm on the fence if it's redudant or the supportApp automatically means that we don't support RHOAI. WDYT?
> 
> @thepetk We don't need the condition. Thanks for the idea however, I have updated my Templates PR a bit and this is now gated by a `SUPPORT_APP` flag (Previously I had two flags, one for app support and one for RHOAI but you are right, RHOAI is only supported for apps right now) https://github.com/redhat-ai-dev/ai-lab-template/pull/59/files#diff-93f04871150a5282f08197ca6fb62209045c4db3f3c3a4b6a8b8abd09a8c4601R398-R401
> 
> and this is the Gitops Kustomize, there is no `rhoai` reference https://github.com/redhat-appstudio-mjf/modelserver-dec17-1-gitops/blob/main/components/modelserver-dec17-1/base/kustomization.yaml

Makes sense. Thanks

**Pull request merged**
