### PR TITLE
Add MODEL_ENDPOINT_BEARER to deployment

### PR DESCRIPTION
**Pull request by thepetk**
### What does this PR do?:
Adds an extra env var taken from a given secret. The env var is an optional API_KEY which (when provided) is used for bearer authentication process during requests to the given model server.

Draft: as it's currently blocked by https://github.com/containers/ai-lab-recipes/pull/790 needs to be merged first and all updates is necessary to be pulled inside the github.com/redhat-ai-dev/ai-lab-samples.  

**UPDATE**: After I've test all non-RHOAI deployments that work fine, I'll apply the same to RHOAI.

### Which issue(s) this PR fixes:
https://issues.redhat.com/browse/DEVAI-158

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened and linked to this PR, if they are not in the PR scope due to various constraints.

- [ ] Tested and Verified

  

- [ ] Documentation (READMEs, Product Docs, Blogs, Education Modules, etc.)

   

### How to test changes / Special notes to the reviewer:
I'll add specific test examples in here and I'll soon open a similar pr on the templates side (updating the template skeleton) with detailed instructions for testing.

### CODE REVIEW

**Review by johnmcollier — COMMENTED** [review]
I know it's still in draft - but we'll want to make the same change to the RHOAI deployment (adding the `MODEL_ENDPOINT_BEARER` env)

**Comment by thepetk** [comment]
> I know it's still in draft - but we'll want to make the same change to the RHOAI deployment (adding the `MODEL_ENDPOINT_BEARER` env)

Yes Ι think is actually my bad as it's not clear from the description. I'm planning indeed to add this part too soon :)

**Comment by thepetk** [comment]
> I know it's still in draft - but we'll want to make the same change to the RHOAI deployment (adding the `MODEL_ENDPOINT_BEARER` env)

Done in [d2be2c0](https://github.com/thepetk/ai-lab-app/commit/d2be2c06f4f3f0da75c5f2d61f50087fb7f5eb6f)

**Comment by thepetk** [comment]
In terms of non-RHOAI deployments, I've gone through the following tests:

### Audio-to-text:
audio-to-text

As audio-to-text uses a whisper.cpp model, I've deployed my own 3scale instance, ran locally whisper.cpp and exposed it through ngrok. I added the model then to 3scale so I can use api cast to verify that authentication works.

### Chatbot:
chatbot-secret

Chatbot was tested with our deployed model service.

### Codegen:
codegen-secret

Codegen app was tested using our deployed model service.

### Object detection
object-detection-secret

Similar to audio to text the model had to be ran locally, exposed through ngrok and integrated to 3scale.

### Rag
rag-secret

Rag worked nicely too with our model service.

**Comment by thepetk** [comment]
RHOAI tests have been completed too:

* I've used RAG sample and I was able to communicate with our model-service :)
image

**Review by maysunfaisal — APPROVED** [review]

**Comment by maysunfaisal** [comment]
> As audio-to-text uses a whisper.cpp model, I've deployed my own 3scale instance, ran locally whisper.cpp and exposed it through ngrok. I added the model then to 3scale so I can use api cast to verify that authentication works.

@thepetk do you have a step-step doc so that I can try this approach out too

**Comment by thepetk** [comment]
> > As audio-to-text uses a whisper.cpp model, I've deployed my own 3scale instance, ran locally whisper.cpp and exposed it through ngrok. I added the model then to 3scale so I can use api cast to verify that authentication works.
> 
> @thepetk do you have a step-step doc so that I can try this approach out too

@maysunfaisal oof that was complicated tbh, but I totally agree and is a fair point as I haven't provided context to the reviewer so everyone can review. I'll try to add additional  instructions below:

## Background

The `audio-to-text` recipe is currently using the [whisper.cpp](https://github.com/ggerganov/whisper.cpp) server, which is quite different than a model server that is using the `whisper-1` model. That said, it was impossible to test the recipe against for example the `OpenAI` `whisper` model.

The main issue with this approach is that the `whisper.cpp` doesn't support the bearer authentication atm, so we need to create an environment where `whisper.cpp` is served behind a service that ensures bearer authentication. My prefered way was:

* Run whisper.cpp image locally.
* Expose the local server with HTTPS using `ngrok`.
* Start an openshift cluster.
* Install the 3scale operator and create a 3scale api manager instance.
* Create a product having a backend using the exposed `whisper.cpp` server.
* Configure 3scale to follow the JWT Bearer authentication flow.

Following the above you'll be able to get a URL from API cast, serving your exposed whisper.cpp model server and standing behind a service that supports bearer auth.

## Run whisper.cpp image locally

Follow the instructions in the [model_server repo](https://github.com/containers/ai-lab-recipes/tree/main/model_servers/whispercpp#whisper) on how to setup & run locally `whisper.cpp` model server.

## Expose the local server with HTTPS using `ngrok`

It's a fairly easy process, if you have `ngrok` installed simply run `ngrok http <your-servers-port>`. For further information I'd suggest taking a look at this [post](https://reyhann.medium.com/how-to-expose-your-localhost-server-using-ngrok-9928ac2e26b8)

## Start an openshift cluster

I used the [openshift installer](https://github.com/openshift/installer?tab=readme-ov-file#openshift-installer) project. This requires specific access to get it working. I'd also recommend starting a cluster with cluster bot or using [CRC](https://www.redhat.com/sysadmin/codeready-containers).

## Install the 3scale operator and create a 3scale api manager instance.

I've captured the necessary steps [here](https://docs.google.com/document/d/1g0niHaMYAhhDZpbPncnr5ZvDhJnE6T-qN3CTkBOnY9o/edit#heading=h.m26rz99al3dj). This link needs permissions, alternative resources are:
*  [1](https://docs.redhat.com/en/documentation/red_hat_3scale_api_management/2.8/html/installing_3scale/install-threescale-on-openshift-guide), [2](https://croz.net/deploy-3scale-into-the-red-hat-openshift-local-ex-crc/), [3](https://auscunningham.medium.com/kicking-the-tires-of-3scale-api-management-with-the-operator-866b27856e5a)


## Create a product having a backend using the exposed `whisper.cpp` server

The first time you access your `3scale-admin` portal (url is `3scale-admin.<baseClusterURL>`) you'll enter a wizzard that helps you create the very first product of this instance. As backend private url add the exposed https url created from `ngrok`.

Creds to access the admin portal can be found to the secret called `system-seed` inside the namespace of the 3scale-operator.

## Configure 3scale to follow the JWT Bearer authentication flow.

3scale by default doesn't have JWT auth enabled. Users can authenticate using the `user_key` for their product (can be found in the developer's app section).

For the tests I've made I simply combined HTTP Header Authentication with `user_key` as the authentication header to avoid the full JWT approach. I consider it to be the same as it worked for our already deployed models and is something that is related only to the 3scale confguration.

If you'd like to add JWT auth you should (thanks @johnmcollier for the help on this step :) ):

* Follow the steps [here](https://github.com/rh-aiservices-bu/models-aas?tab=readme-ov-file#deployment-1) to import the Remove Bearer custom policy into `3scale`.
* Go to the product you want to configure Bearer auth support, select `Integration` -> `Policies`. Add the policies in this order: (You may need to rearrange the policies to be in that order)
```
1. CORS Request Handling:
        - ALLOW_HEADERS: Authorization, Content-type, Accept.
        - allow_origin: *
        - allow_credentials: checked
2. Remove Bearer from Authorization Policy
3. 3scale APIcast
```
* Click Update Policy chain
* Go to `Integration` -> `Settings` under your product
* Change `API Key` name to `Authorization`
* Change Credentials Location to `HTTP Header`

## Troubleshooting

* In case your software template deployment gets an HTTPS verification error you need to update your software's template repo and set `verify=False` to your `requests` method. This way you disable raising an exception if the request your python app makes is targeting an unverified source.

**Pull request merged**
