### PR TITLE
Update DSP init job for new image

### PR DESCRIPTION
**Pull request by maysunfaisal**
### What does this PR do?:

- Forgot to push the new image as part of https://github.com/redhat-ai-dev/ai-lab-app/pull/26
- Just updated capitalization on the echo statements

### Which issue(s) this PR fixes:

https://issues.redhat.com/browse/DEVAI-89

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened and linked to this PR, if they are not in the PR scope due to various constraints.

- [x] Tested and Verified

  

- [ ] Documentation (READMEs, Product Docs, Blogs, Education Modules, etc.)

### CODE REVIEW

**Review by Jdubrick — APPROVED** [review]
lgtm

**Comment by thepetk** [comment]
@maysunfaisal is it ok to use the same [template](https://github.com/maysunfaisal/ai-lab-template/blob/DEVAI-89-12e/templates/rag/template.yaml) for testing this one too?

**Comment by maysunfaisal** [comment]
@thepetk the template you linked uses this image https://github.com/maysunfaisal/ai-lab-template/blob/DEVAI-89-12e/skeleton/gitops-template/components/http/base/rhoai/initialize-dsp.yaml#L119

I just forgot to copy paste and noticed that I missed it when I tried to generate/import in template repo.

**Review by thepetk — APPROVED** [review]
/lgtm as the change should be already tested for https://github.com/redhat-ai-dev/ai-lab-app/pull/26

**Pull request merged**
