### PR TITLE
Mirror quay images to redhat-ai-dev

### PR DESCRIPTION
**Pull request by Jdubrick**
### What does this PR do?:

This PR mirrors the `quay.io` images to `redhat-ai-dev`. You can find the mirrored image here: https://quay.io/repository/redhat-ai-dev/appstudio-utils?tab=tags

### Which issue(s) this PR fixes:

Part of https://issues.redhat.com/browse/DEVAI-37

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened and linked to this PR, if they are not in the PR scope due to various constraints.

- [ ] Tested and Verified

  

- [ ] Documentation (READMEs, Product Docs, Blogs, Education Modules, etc.)

### CODE REVIEW

**Comment by yangcao77** [comment]
Can we have this image containerfile under `redhat-ai-dev/developer-images`?
And I'm assuming you have tested the namespace creation & component deployment?

**Comment by Jdubrick** [comment]
> Can we have this image containerfile under `redhat-ai-dev/developer-images`? And I'm assuming you have tested the namespace creation & component deployment?

This is just a simple `pull` of `quay.io/redhat-appstudio/appstudio-utils:5bd7d6cb0b17f9f2eab043a8ad16ba3d90551bc2@sha256:8c7fcf86af40c71aeb58e4279625c8308af5144e2f6b8e28b0ec7e795260e5f7` and retagging it to push to `redhat-ai-dev` so I didn't have to build it from the containerfile but I can try and find it. If we're truly mirroring though I'm unsure if we want to maintain containerfiles? 

As for the deployment test I am waiting on a cluster but I don't expect any issues since it is a direct mirror

**Comment by maysunfaisal** [comment]
yeah I think we can avoid Containerfiles if its a direct 1:1 mirror. I asked @Jdubrick to update the quay.io image repo page description so that we know there is no Container and its a direct 1:1 mirror

**Comment by Jdubrick** [comment]
Marking as WIP since my installer isn't cooperating so I need to debug that install first.

**Comment by Jdubrick** [comment]
Jobs completing after change: 

Screenshot 2024-08-26 at 6 52 06 PM
Screenshot 2024-08-26 at 6 52 30 PM
Screenshot 2024-08-26 at 6 53 18 PM

Notebook with cloned content:
Screenshot 2024-08-26 at 6 51 43 PM

**Comment by maysunfaisal** [comment]
@Jdubrick just this one image? and do we know if there is a Containerfile since it seems the prior image was created by us 👀

**Comment by Jdubrick** [comment]
> @Jdubrick just this one image? and do we know if there is a Containerfile since it seems the prior image was created by us 👀

@maysunfaisal just this one image for this repo, there is more that need to be updated in [ai-lab-template](https://github.com/redhat-ai-dev/ai-lab-template) and [ai-lab-template-experiment](https://github.com/redhat-ai-dev/ai-lab-template-experiment) but since the changes on this PR would also need to be made in those repos I will pull them in after this is merged.

I looked through https://github.com/redhat-appstudio and couldn't find the containerfile or anything linked on the quay repo but I can keep looking

**Review by maysunfaisal — APPROVED** [review]
yes, i would like if we could keep an eye on the containerfile and maybe just make a note of it in the repo description,

otherwise lgtm

**Comment by Jdubrick** [comment]
> yes, i would like if we could keep an eye on the containerfile and maybe just make a note of it in the repo description,
> 
> otherwise lgtm

When you said `seems the prior image was created by us` did you mean Red Hat or our team? If our team then surely the containerfile is somewhere

**Comment by maysunfaisal** [comment]
> > yes, i would like if we could keep an eye on the containerfile and maybe just make a note of it in the repo description,
> > otherwise lgtm
> 
> When you said `seems the prior image was created by us` did you mean Red Hat or our team? If our team then surely the containerfile is somewhere

@Jdubrick I meant appstudio devs in general. But I couldnt find it either. Can you post on our Slack? Maybe someone will know the origin.

**Pull request merged**
